all:
  children:
    controller:
      hosts:
        controller:
          ansible_host: 192.168.30.60
    workers:
      hosts:
        worker1:
          ansible_host: 192.168.30.61
        worker2:
          ansible_host: 192.168.30.62
    k8s_cluster:
      children:
        controller:
        workers:
